CREATE TABLE IF NOT EXISTS gauges (
    name    VARCHAR NOT NULL PRIMARY KEY,
    value   DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS counters (
    name    VARCHAR NOT NULL PRIMARY KEY,
    delta   BIGINT NOT NULL
);
